"use client";
import { useEffect, useState } from "react";
import { addTripPlanToRouteCollection, createRouteCollection } from "@/app/actions/collections";
import { supabase } from "@/lib/supabase";

type Collection = { id: string; title: string };
export function SaveTripToRouteCollection({ tripPlanId }: { tripPlanId: string }) {
  const [collections, setCollections] = useState<Collection[]>([]); const [selected, setSelected] = useState(""); const [newTitle, setNewTitle] = useState(""); const [message, setMessage] = useState(""); const [isSaving, setIsSaving] = useState(false);
  const load = async () => { const { data, error } = await (supabase as any).from("route_collections").select("id,title").order("created_at"); if (error) setMessage(error.message); else setCollections(data ?? []); };
  useEffect(() => { void load(); }, []);
  const add = async () => { if (!selected) return; setIsSaving(true); try { await addTripPlanToRouteCollection(selected, tripPlanId); setMessage("Added to route collection."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to add this journey."); } finally { setIsSaving(false); } };
  const create = async () => { const title = newTitle.trim(); if (!title) return; setIsSaving(true); try { const collection = await createRouteCollection(title); await addTripPlanToRouteCollection(collection.id, tripPlanId); setSelected(collection.id); setCollections((items) => [...items, collection]); setMessage(`Created ${title} and added this route.`); setNewTitle(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create this collection."); } finally { setIsSaving(false); } };
  return <div className="mt-4 border-t border-cyan-400/20 pt-4"><p className="text-sm font-medium">Add to a route collection</p><p className="mt-1 text-xs text-muted-foreground">Keep this saved journey with other routes, or create a new route collection now.</p><div className="mt-2 flex flex-wrap gap-2"><select value={selected} onChange={(e) => setSelected(e.target.value)} className="rounded-lg border border-border bg-background px-3 py-2 text-sm"><option value="">Choose existing collection</option>{collections.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><button type="button" onClick={() => void add()} disabled={!selected || isSaving} className="rounded-lg border border-cyan-400/40 px-3 py-2 text-sm text-cyan-200 disabled:opacity-50">{isSaving ? "Saving…" : "Add"}</button></div><div className="mt-2 flex flex-wrap gap-2"><input value={newTitle} onChange={(e) => setNewTitle(e.target.value)} placeholder="New route collection name" className="rounded-lg border border-border bg-background px-3 py-2 text-sm"/><button type="button" onClick={() => void create()} disabled={!newTitle.trim() || isSaving} className="rounded-lg bg-cyan-400 px-3 py-2 text-sm font-medium text-slate-950 disabled:opacity-50">Create & add</button></div>{message && <p className="mt-2 text-xs text-cyan-200" role="status">{message}</p>}</div>;
}
