"use client";

import { type FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";

import Navbar from "@/components/layout/navbar";
import { isStrongPassword, PASSWORD_REQUIREMENTS_MESSAGE } from "@/components/auth/auth-request";
import { supabase } from "@/lib/supabase";

export default function ResetPasswordPage() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [code, setCode] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!isStrongPassword(password)) { setMessage(PASSWORD_REQUIREMENTS_MESSAGE); return; } setLoading(true); setMessage(""); const { error: verificationError } = await supabase.auth.verifyOtp({ email: email.trim().toLowerCase(), token: code.trim(), type: "recovery" }); if (verificationError) { setLoading(false); setMessage("That recovery code is invalid or has expired. Request a new one."); return; } const { error } = await supabase.auth.updateUser({ password }); setLoading(false); if (error) { setMessage("We could not reset the password. Request a new recovery code and try again."); return; } router.replace("/sign-in"); router.refresh(); };
  return <main className="min-h-screen bg-background"><Navbar /><section className="mx-auto flex min-h-[calc(100vh-4rem)] max-w-md items-center px-4 py-16"><div className="w-full rounded-2xl border border-border bg-card p-6"><p className="text-sm font-medium text-cyan-300">Account recovery</p><h1 className="mt-2 text-3xl font-bold">Choose a new password</h1><p className="mt-3 text-sm text-muted-foreground">Enter the one-time code from the recovery email. It is single-use and expires within one hour.</p><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-medium">Email address<input required type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 w-full rounded-lg border border-border bg-background px-3 py-3" /></label><label className="block text-sm font-medium">Recovery code<input required inputMode="numeric" autoComplete="one-time-code" value={code} onChange={(event) => setCode(event.target.value)} className="mt-2 w-full rounded-lg border border-border bg-background px-3 py-3" /></label><label className="block text-sm font-medium">New password<input required type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-lg border border-border bg-background px-3 py-3" /></label><p className="text-xs text-muted-foreground">{PASSWORD_REQUIREMENTS_MESSAGE}</p>{message && <p className="rounded-lg bg-cyan-400/10 p-3 text-sm text-cyan-100">{message}</p>}<button disabled={loading} className="w-full rounded-lg bg-cyan-400 px-4 py-3 font-semibold text-slate-950 disabled:opacity-60">{loading ? "Please wait…" : "Reset password"}</button></form><Link href="/forgot-password" className="mt-5 inline-block text-sm text-cyan-300 hover:underline">Request a new code</Link></div></section></main>;
}
