-- Generated from darjeeling, srinagar using 4 throttled Google Places requests.
with seed (slug, destination_slug, category_slug, name, address, latitude, longitude, google_place_id, source_url, description) as (
  values
    ('observatory-hill-view-point-darjeeling', 'darjeeling', 'viewpoints', 'Observatory Hill View Point', '27X8+XC2, Naya Basti, Darjeeling, West Bengal 734101, India', 27.049895499999998, 88.2660303, 'ChIJjVWmo8Au5DkR7AnS-TpX5gw', 'https://maps.google.com/?cid=929526283909597676&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Observatory Hill View Point is a Google Places sourced visitor location in Darjeeling.'),
    ('tiger-hill-observatory-sunrise-viewpoint-darjeeling', 'darjeeling', 'viewpoints', 'Tiger Hill Observatory/ Sunrise Viewpoint', 'Senchal Rd, Senchal Forest, West Bengal 734102, India', 26.9948256, 88.2852338, 'ChIJG0XgMcsv5DkRjaLxQIj2nks', 'https://maps.google.com/?cid=5449063664230441613&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Tiger Hill Observatory/ Sunrise Viewpoint is a Google Places sourced visitor location in Darjeeling.'),
    ('kanchenjunga-view-point-darjeeling', 'darjeeling', 'viewpoints', 'Kanchenjunga-View Point', '3737+2H7, Naya Basti, Darjeeling, Rungneet Tea Garden, West Bengal 734104, India', 27.0525421, 88.2639222, 'ChIJWzR8wrgu5DkRZKOtwZjgQT8', 'https://maps.google.com/?cid=4558171244564685668&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Kanchenjunga-View Point is a Google Places sourced visitor location in Darjeeling.'),
    ('mahakal-temple-viewpoint-darjeeling', 'darjeeling', 'viewpoints', 'Mahakal temple viewpoint', '27X9+GQ6, Upper Bhutia Busty, Darjeeling, West Bengal 734101, India', 27.048401, 88.26899499999999, 'ChIJt4eYxPov5DkR99VTCPdoFeA', 'https://maps.google.com/?cid=16146927449212704247&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Mahakal temple viewpoint is a Google Places sourced visitor location in Darjeeling.'),
    ('glenary-s-bakery-resturant-pub-darjeeling', 'darjeeling', 'cafes', 'Glenary''s— Bakery, Resturant & Pub', 'Nehru Rd, near Clock Tower, Chauk Bazaar, Darjeeling, West Bengal 734101, India', 27.0430162, 88.26694529999999, 'ChIJt2_v6Oou5DkRDJ4yqWaK5MQ', 'https://maps.google.com/?cid=14187616899653869068&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Glenary''s— Bakery, Resturant & Pub is a Google Places sourced cafe or food venue in Darjeeling.'),
    ('sol-cafe-darjeeling', 'darjeeling', 'cafes', 'SOL Café', 'SOL Café and Studio, Gandhi Rd, near Hotel Vceroy, Limbugaon, Darjeeling, West Bengal 734101, India', 27.039417399999998, 88.2658072, 'ChIJu5NXQccv5DkRAeDFpJ4gTtY', 'https://maps.google.com/?cid=15442316038041362433&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'SOL Café is a Google Places sourced cafe or food venue in Darjeeling.'),
    ('himalayan-coffee-darjeeling', 'darjeeling', 'cafes', 'Himalayan Coffee', 'Nehru Rd, Chauk Bazaar, Darjeeling, West Bengal 734101, India', 27.0438679, 88.26741589999999, 'ChIJUcXUHesu5DkRYv8N7-qJ8fM', 'https://maps.google.com/?cid=17577982462729781090&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Himalayan Coffee is a Google Places sourced cafe or food venue in Darjeeling.'),
    ('keventer-s-darjeeling', 'darjeeling', 'cafes', 'Keventer''s', 'Shop No. 1, Club Side, Nehru Rd, Chauk Bazaar, Darjeeling, West Bengal 734101, India', 27.0420591, 88.26657809999999, 'ChIJc6iFGOsu5DkRUKmxWULO4y0', 'https://maps.google.com/?cid=3306713335788054864&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Keventer''s is a Google Places sourced cafe or food venue in Darjeeling.'),
    ('tom-jerry-cafe-s-darjeeling', 'darjeeling', 'cafes', 'Tom & Jerry Cafe’s', 'Dr Zakir Hussain Rd, Tungsung Basti, Darjeeling, Pandam Tea Garden, West Bengal 734201, India', 27.042490899999997, 88.2680085, 'ChIJ4_I8Qusu5DkRYBbeKZ5Wg_U', 'https://maps.google.com/?cid=17691078998548682336&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Tom & Jerry Cafe’s is a Google Places sourced cafe or food venue in Darjeeling.'),
    ('chashme-shahi-garden-srinagar', 'srinagar', 'viewpoints', 'Chashme Shahi Garden', '7, Boulevard Road, Chashma Shahi, Rainawari, Srinagar, 191121', 34.0858864, 74.8869056, 'ChIJM_X0TKWI4TgROXG94YYSHgQ', 'https://maps.google.com/?cid=296694995975237945&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Chashme Shahi Garden is a Google Places sourced visitor location in Srinagar.'),
    ('shankaracharya-view-point-srinagar', 'srinagar', 'viewpoints', 'Shankaracharya View point', '3RHQ+FX, Durgjan, Srinagar, 190001', 34.078706, 74.8398764, 'ChIJ6cgJqu6P4TgRmloCzgazE_k', 'https://maps.google.com/?cid=17947885781808994970&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Shankaracharya View point is a Google Places sourced visitor location in Srinagar.'),
    ('view-point-ghat-srinagar', 'srinagar', 'viewpoints', 'View point ghat', '4RWW+9M, Srinagar, 190006', 34.1459007, 74.8466315, 'ChIJPQX7jXqF4TgR1kCu_UUk6p4', 'https://maps.google.com/?cid=11451004885570306262&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'View point ghat is a Google Places sourced visitor location in Srinagar.'),
    ('dal-view-point-srinagar', 'srinagar', 'viewpoints', 'Dal View point', 'Houseboat Newswift Dal lake, ghat number 12, srinagar, Gagribal, Srinagar, 190001', 34.087134, 74.8483589, 'ChIJeUozrSOP4TgRI_TR7bc7QsM', 'https://maps.google.com/?cid=14069873847013864483&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Dal View point is a Google Places sourced visitor location in Srinagar.'),
    ('pari-mahal-srinagar', 'srinagar', 'viewpoints', 'Pari Mahal', '3VJG+FVC, near Pari Mahal Parking, Srinagar, 191121', 34.081193899999995, 74.877152, 'ChIJI7OGp7OI4TgRw7xBy0TCdyE', 'https://maps.google.com/?cid=2411609726203837635&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Pari Mahal is a Google Places sourced visitor location in Srinagar.'),
    ('majlis-eatery-specialty-coffee-srinagar', 'srinagar', 'cafes', 'Majlis Eatery & Specialty Coffee', '1st Floor, Polo Plaza, Polo View Road, Regal Chowk, Market, Munshi Bagh, Srinagar, 190001', 34.0737198, 74.8199624, 'ChIJx4l1RNSP4TgR4THH9SLHPUk', 'https://maps.google.com/?cid=5277593291314377185&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Majlis Eatery & Specialty Coffee is a Google Places sourced cafe or food venue in Srinagar.'),
    ('winterfell-cafe-srinagar', 'srinagar', 'cafes', 'Winterfell Café', 'Hotel Paradise Complex Boulevard Road, opposite ghat no 5, Durgjan, Srinagar, 190001', 34.0820147, 74.8335124, 'ChIJA-E-0XuP4TgRPI2uWJ4e_MQ', 'https://maps.google.com/?cid=14194253791006461244&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Winterfell Café is a Google Places sourced cafe or food venue in Srinagar.'),
    ('the-backyard-grill-srinagar', 'srinagar', 'cafes', 'The Backyard Grill', '19-A, Rajbagh, Srinagar, 190008', 34.0671384, 74.82418369999999, 'ChIJD9x1LiyP4TgRCFTv6LBtq3A', 'https://maps.google.com/?cid=8118703359855121416&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'The Backyard Grill is a Google Places sourced cafe or food venue in Srinagar.'),
    ('the-black-vintage-srinagar', 'srinagar', 'cafes', 'The Black Vintage', 'radio colony, Rajbagh, Srinagar, 190008', 34.064448, 74.81961059999999, 'ChIJi792w-OP4TgRcjzf43l5nkg', 'https://maps.google.com/?cid=5232753381472156786&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'The Black Vintage is a Google Places sourced cafe or food venue in Srinagar.'),
    ('meydani-cafe-srinagar', 'srinagar', 'cafes', 'Meydani Cafe', 'The Bund Road, Residency Road, near Chai Jai, Poloview, Munshi Bagh, Srinagar, 190001', 34.0719668, 74.8216271, 'ChIJZaVxQKOP4TgREhdVbHL3fGk', 'https://maps.google.com/?cid=7601222341910402834&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Meydani Cafe is a Google Places sourced cafe or food venue in Srinagar.')
)
insert into public.places (slug, name, level, parent_id, city, state, country, location, address, description, google_place_id, source_url, source_reference, last_verified_at, is_published, is_external, external_source, external_details)
select seed.slug, seed.name, 'attraction'::public.place_level, destination.id, destination.name, destination.state, destination.country, st_setsrid(st_makepoint(seed.longitude, seed.latitude), 4326)::geography, seed.address, seed.description, seed.google_place_id, nullif(seed.source_url, ''), 'Google Places Text Search - controlled catalogue batch', now(), true, false, 'google_places', jsonb_build_object('catalogue_batch', 'generated-google')
from seed join public.places destination on destination.slug = seed.destination_slug
on conflict (slug) do update set parent_id = excluded.parent_id, city = excluded.city, state = excluded.state, country = excluded.country, location = excluded.location, address = excluded.address, description = excluded.description, google_place_id = excluded.google_place_id, source_url = excluded.source_url, source_reference = excluded.source_reference, last_verified_at = excluded.last_verified_at, is_published = true, is_external = false, external_source = excluded.external_source, external_details = excluded.external_details, updated_at = now();

with seed (slug, category_slug) as (values ('observatory-hill-view-point-darjeeling', 'viewpoints'), ('tiger-hill-observatory-sunrise-viewpoint-darjeeling', 'viewpoints'), ('kanchenjunga-view-point-darjeeling', 'viewpoints'), ('kanchenjunga-view-point-darjeeling', 'viewpoints'), ('mahakal-temple-viewpoint-darjeeling', 'viewpoints'), ('glenary-s-bakery-resturant-pub-darjeeling', 'cafes'), ('sol-cafe-darjeeling', 'cafes'), ('himalayan-coffee-darjeeling', 'cafes'), ('keventer-s-darjeeling', 'cafes'), ('tom-jerry-cafe-s-darjeeling', 'cafes'), ('chashme-shahi-garden-srinagar', 'viewpoints'), ('shankaracharya-view-point-srinagar', 'viewpoints'), ('view-point-ghat-srinagar', 'viewpoints'), ('dal-view-point-srinagar', 'viewpoints'), ('pari-mahal-srinagar', 'viewpoints'), ('majlis-eatery-specialty-coffee-srinagar', 'cafes'), ('winterfell-cafe-srinagar', 'cafes'), ('the-backyard-grill-srinagar', 'cafes'), ('the-black-vintage-srinagar', 'cafes'), ('meydani-cafe-srinagar', 'cafes'))
insert into public.place_categories (place_id, category_id)
select place.id, category.id from seed join public.places place on place.slug = seed.slug join public.categories category on category.slug = seed.category_slug
on conflict do nothing;
