-- Generated from ahmedabad, chandigarh using 4 throttled Google Places requests.
with seed (slug, destination_slug, category_slug, name, address, latitude, longitude, google_place_id, source_url, description) as (
  values
    ('baps-shri-swaminarayan-mandir-ahmedabad', 'ahmedabad', 'temples', 'BAPS Shri Swaminarayan Mandir', 'Shahibaug Rd., Jain Colony, Shahibag, Ahmedabad, Gujarat 380004, India', 23.045043399999997, 72.59004209999999, 'ChIJR2eiImuEXjkRw7CRwV6AsnM', 'https://maps.google.com/?cid=8336867004679041219&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'BAPS Shri Swaminarayan Mandir is a Google Places sourced visitor location in Ahmedabad.'),
    ('shri-jagannathji-mandir-ahmedabad-ahmedabad', 'ahmedabad', 'temples', 'Shri Jagannathji Mandir, Ahmedabad', 'At, Jamalpur Darwaja, Jamalpur, Ahmedabad, Gujarat 380022, India', 23.0114004, 72.581049, 'ChIJe1mxJLKFXjkRQoP_zkVIqkc', 'https://maps.google.com/?cid=5164019387396490050&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Shri Jagannathji Mandir, Ahmedabad is a Google Places sourced visitor location in Ahmedabad.'),
    ('hutheesing-jain-temple-ahmedabad', 'ahmedabad', 'temples', 'Hutheesing Jain Temple', 'Hutheesing Jain Temple, 40, Shahibaug Rd., Bardolpura, Madhupura, Ahmedabad, Gujarat 380016, India', 23.0410997, 72.5894749, 'ChIJq744I0CEXjkRmRSLZ_9dtm8', 'https://maps.google.com/?cid=8049724735506551961&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Hutheesing Jain Temple is a Google Places sourced visitor location in Ahmedabad.'),
    ('baps-shri-swaminarayan-akshardham-gandhinagar-ahmedabad', 'ahmedabad', 'temples', 'BAPS Shri Swaminarayan Akshardham, Gandhinagar', 'J Road, Sector 20, Gandhinagar, Gujarat 382021, India', 23.2293681, 72.6740587, 'ChIJ6dhnAQ4rXDkRJmHw0T2Wd5c', 'https://maps.google.com/?cid=10914357414215049510&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'BAPS Shri Swaminarayan Akshardham, Gandhinagar is a Google Places sourced visitor location in Ahmedabad.'),
    ('iskcon-temple-ahmedabad-ahmedabad', 'ahmedabad', 'temples', 'ISKCON Temple, Ahmedabad', 'Satellite Road, Sarkhej - Gandhinagar Hwy, Bodakdev, Ahmedabad, Gujarat 380059, India', 23.0282898, 72.50689129999999, 'ChIJ8_qnyIqEXjkR6UBgjDrwJvI', 'https://maps.google.com/?cid=17448897940547453161&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'ISKCON Temple, Ahmedabad is a Google Places sourced visitor location in Ahmedabad.'),
    ('bhadra-fort-ahmedabad', 'ahmedabad', 'forts', 'Bhadra Fort', '2HFJ+MCX, Bhadra Rd, Old City, Lal Darwaja, Ahmedabad, Gujarat 380001, India', 23.0242343, 72.5811181, 'ChIJxcxtE06EXjkRYp2USYsE5nw', 'https://maps.google.com/?cid=8999885901627956578&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Bhadra Fort is a Google Places sourced visitor location in Ahmedabad.'),
    ('teen-darwaja-ahmedabad', 'ahmedabad', 'forts', 'Teen Darwaja', 'Teen darvaja, Old City, Bhadra, Ahmedabad, Gujarat 380001, India', 23.0243941, 72.58455099999999, 'ChIJZzmqBUGEXjkRsiIR8EjRoLg', 'https://maps.google.com/?cid=13303863410447950514&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Teen Darwaja is a Google Places sourced visitor location in Ahmedabad.'),
    ('fateh-baug-fort-palace-ahmedabad', 'ahmedabad', 'forts', 'Fateh Baug Fort Palace', 'XG85+HGP, Sarkhej-Okaf, Ahmedabad, Gujarat 380055, India', 22.9664549, 72.5088383, 'ChIJaXyArhGbXjkRmVM8OFwrIsc', 'https://maps.google.com/?cid=14349079037836284825&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Fateh Baug Fort Palace is a Google Places sourced visitor location in Ahmedabad.'),
    ('nagardevi-shri-bhadrakali-mata-temple-ahmedabad', 'ahmedabad', 'forts', 'Nagardevi Shri Bhadrakali Mata Temple', 'Bhadra Fort, Bhadra Rd, Old City, Bhadra, Ahmedabad, Gujarat 380001, India', 23.024076299999997, 72.5816713, 'ChIJu7CUb06EXjkRCT9PrCABZ44', 'https://maps.google.com/?cid=10261171515828420361&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Nagardevi Shri Bhadrakali Mata Temple is a Google Places sourced visitor location in Ahmedabad.'),
    ('kaligam-fort-ahmedabad', 'ahmedabad', 'forts', 'kaligam fort', '3HVF+JWQ, opp. Government Aganwadi, Railway Colony, Kali, Ahmedabad, Gujarat 382470, India', 23.0939032, 72.57470889999999, 'ChIJe_o1LwCDXjkRHx_YVP7khcI', 'https://maps.google.com/?cid=14016861196256812831&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'kaligam fort is a Google Places sourced visitor location in Ahmedabad.'),
    ('iskcon-temple-chandigarh-chandigarh', 'chandigarh', 'temples', 'ISKCON Temple Chandigarh', 'Hare Krishna dham, ISKCON Temple, Dakshin Marg, Sector-36B, Sector 36, Chandigarh, 160036, India', 30.734366199999997, 76.76134590000001, 'ChIJOUvVMLntDzkRgBKx9y3rsX8', 'https://maps.google.com/?cid=9201394096356266624&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'ISKCON Temple Chandigarh is a Google Places sourced visitor location in Chandigarh.'),
    ('shri-radha-krishna-temple-18c-chandigarh-chandigarh', 'chandigarh', 'temples', 'Shri Radha Krishna Temple, 18C Chandigarh', 'PQJP+8FM, Udyog Path, Sector 18-C, Sector 18, Chandigarh, 160018, India', 30.730846300000003, 76.7861666, 'ChIJqzLz7wXtDzkRo2dx7JKUVMA', 'https://maps.google.com/?cid=13858865312078849955&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Shri Radha Krishna Temple, 18C Chandigarh is a Google Places sourced visitor location in Chandigarh.'),
    ('shirdi-sai-samaj-sai-temple-chandigarh', 'chandigarh', 'temples', 'Shirdi Sai Samaj Sai Temple', '6, Sai Baba Rd, Ordnance Cable Factory Colony, B Sector 29, Sector 29, Chandigarh, 160030, India', 30.711635800000003, 76.7916001, 'ChIJxb7qM-XsDzkRdZBjmWDjnvc', 'https://maps.google.com/?cid=17842948777718288501&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Shirdi Sai Samaj Sai Temple is a Google Places sourced visitor location in Chandigarh.'),
    ('shri-mata-mansa-devi-mandir-panchkula-chandigarh', 'chandigarh', 'temples', 'Shri Mata Mansa Devi Mandir, Panchkula', 'PVF6+F7J, Mansa Devi Complex, MDC Sector 4, Panchkula, Haryana 134114, India', 30.723712499999994, 76.8606406, 'ChIJq6qqahuTDzkRMg2sYAX6aH0', 'https://maps.google.com/?cid=9036747553322569010&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Shri Mata Mansa Devi Mandir, Panchkula is a Google Places sourced visitor location in Chandigarh.'),
    ('shri-karthikeya-swami-temple-31d-chandigarh-chandigarh', 'chandigarh', 'temples', 'Shri Karthikeya Swami Temple, 31D Chandigarh', 'Sector 31, 31D, 31-D, Chandigarh, 160030, India', 30.7034539, 76.7767187, 'ChIJs8kcJ1nsDzkRyuHhxBW01iU', 'https://maps.google.com/?cid=2726564630009864650&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Shri Karthikeya Swami Temple, 31D Chandigarh is a Google Places sourced visitor location in Chandigarh.'),
    ('the-fort-ramgarh-chandigarh', 'chandigarh', 'forts', 'The Fort Ramgarh', 'NH 7, opposite Sector 28, Panchkula, Haryana 134118, India', 30.6477748, 76.8855179, 'ChIJy8TNRE6UDzkRzrWFTquDJfY', 'https://maps.google.com/?cid=17736727479248598478&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'The Fort Ramgarh is a Google Places sourced visitor location in Chandigarh.'),
    ('burj-fort-chandigarh', 'chandigarh', 'forts', 'Burj Fort', 'Morni Hills Road, Post, Burj, Chandi Mandir, Panchkula, Haryana 134102, India', 30.7377181, 76.9124176, 'ChIJJSioiiuSDzkR1SubimA2vx4', 'https://maps.google.com/?cid=2215549329959758805&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Burj Fort is a Google Places sourced visitor location in Chandigarh.'),
    ('the-morni-fort-panchkula-district-haryana-india-chandigarh', 'chandigarh', 'forts', 'The Morni Fort - Panchkula district, Haryana, India', 'Panchkula - Badiyal Rd, Morni, Bhoj Balig, Haryana 134205, India', 30.688616699999994, 77.0831439, 'ChIJWe-6fkGZDzkRmBoGM15c0eY', 'https://maps.google.com/?cid=16632176458508671640&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'The Morni Fort - Panchkula district, Haryana, India is a Google Places sourced visitor location in Chandigarh.'),
    ('manimajra-fort-chandigarh', 'chandigarh', 'forts', 'Manimajra Fort', '1637, near fort Manimajra, Mohalla Araiyan Wala, Sector 13, Chandigarh, Panchkula, Chandigarh 160101, India', 30.714425799999997, 76.83748709999999, 'ChIJMwaRrDqTDzkRCeRob_wsPjo', 'https://maps.google.com/?cid=4196841365468406793&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Manimajra Fort is a Google Places sourced visitor location in Chandigarh.'),
    ('manauli-fort-chandigarh', 'chandigarh', 'forts', 'MANAULI FORT', 'JPVC+66F Manauli Fort, Manauli Fort, Sector 83, JLPL Industrial Area, Manauli, Punjab 140306, India', 30.6437442, 76.724363, 'ChIJAQDArWfpDzkRhMGjm9KA4Gw', 'https://maps.google.com/?cid=7845412192922091908&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'MANAULI FORT is a Google Places sourced visitor location in Chandigarh.')
)
insert into public.places (slug, name, level, parent_id, city, state, country, location, address, description, google_place_id, source_url, source_reference, last_verified_at, is_published, is_external, external_source, external_details)
select seed.slug, seed.name, 'attraction'::public.place_level, destination.id, destination.name, destination.state, destination.country, st_setsrid(st_makepoint(seed.longitude, seed.latitude), 4326)::geography, seed.address, seed.description, seed.google_place_id, nullif(seed.source_url, ''), 'Google Places Text Search - controlled catalogue batch', now(), true, false, 'google_places', jsonb_build_object('catalogue_batch', 'generated-google')
from seed join public.places destination on destination.slug = seed.destination_slug
on conflict (slug) do update set parent_id = excluded.parent_id, city = excluded.city, state = excluded.state, country = excluded.country, location = excluded.location, address = excluded.address, description = excluded.description, google_place_id = excluded.google_place_id, source_url = excluded.source_url, source_reference = excluded.source_reference, last_verified_at = excluded.last_verified_at, is_published = true, is_external = false, external_source = excluded.external_source, external_details = excluded.external_details, updated_at = now();

with seed (slug, category_slug) as (values ('baps-shri-swaminarayan-mandir-ahmedabad', 'temples'), ('shri-jagannathji-mandir-ahmedabad-ahmedabad', 'temples'), ('hutheesing-jain-temple-ahmedabad', 'temples'), ('baps-shri-swaminarayan-akshardham-gandhinagar-ahmedabad', 'temples'), ('iskcon-temple-ahmedabad-ahmedabad', 'temples'), ('bhadra-fort-ahmedabad', 'forts'), ('teen-darwaja-ahmedabad', 'forts'), ('fateh-baug-fort-palace-ahmedabad', 'forts'), ('nagardevi-shri-bhadrakali-mata-temple-ahmedabad', 'forts'), ('kaligam-fort-ahmedabad', 'forts'), ('iskcon-temple-chandigarh-chandigarh', 'temples'), ('shri-radha-krishna-temple-18c-chandigarh-chandigarh', 'temples'), ('shirdi-sai-samaj-sai-temple-chandigarh', 'temples'), ('shri-mata-mansa-devi-mandir-panchkula-chandigarh', 'temples'), ('shri-karthikeya-swami-temple-31d-chandigarh-chandigarh', 'temples'), ('the-fort-ramgarh-chandigarh', 'forts'), ('burj-fort-chandigarh', 'forts'), ('the-morni-fort-panchkula-district-haryana-india-chandigarh', 'forts'), ('manimajra-fort-chandigarh', 'forts'), ('manauli-fort-chandigarh', 'forts'))
insert into public.place_categories (place_id, category_id)
select place.id, category.id from seed join public.places place on place.slug = seed.slug join public.categories category on category.slug = seed.category_slug
on conflict do nothing;
