-- Generated from rishikesh, varanasi using 4 throttled Google Places requests.
with seed (slug, destination_slug, category_slug, name, address, latitude, longitude, google_place_id, source_url, description) as (
  values
    ('shree-neelkanth-mahadev-temple-rishikesh', 'rishikesh', 'temples', 'Shree Neelkanth Mahadev Temple', '38JR+C7F, Kotdwar - Pauri Rd, Kotdwar, Uttarakhand 249304, India', 30.0810736, 78.34067499999999, 'ChIJuc7MjTQUCTkRl1VQmnFMLxw', 'https://maps.google.com/?cid=2030926007771354519&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Shree Neelkanth Mahadev Temple is a Google Places sourced visitor location in Rishikesh.'),
    ('trayambakeshwar-temple-rishikesh-rishikesh', 'rishikesh', 'temples', 'Trayambakeshwar Temple, Rishikesh', 'Shiv chowk, near trimbakeshwar temple, Laxman Jhula, Rishikesh, Jonk, Uttarakhand 249302, India', 30.126400599999997, 78.33096069999999, 'ChIJIbW4d1wWCTkR9c64Mq9vttM', 'https://maps.google.com/?cid=15255503586025066229&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Trayambakeshwar Temple, Rishikesh is a Google Places sourced visitor location in Rishikesh.'),
    ('parmarth-niketan-ashram-rishikesh', 'rishikesh', 'temples', 'Parmarth Niketan Ashram', 'Main Market Road, near Ram Jhula, Swarg Ashram, Rishikesh, Uttarakhand 249304, India', 30.118827300000003, 78.3131567, 'ChIJN065thUWCTkRrpCI3XVLzsQ', 'https://maps.google.com/?cid=14181355246236242094&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Parmarth Niketan Ashram is a Google Places sourced visitor location in Rishikesh.'),
    ('shri-bharat-mandir-rishikesh', 'rishikesh', 'temples', 'Shri Bharat Mandir', '9, Ghat Rd, Mayakund, Rishikesh, Uttarakhand 249201, India', 30.1059278, 78.3019621, 'ChIJB3gh2AQWCTkR9VfwcWZfFW0', 'https://maps.google.com/?cid=7860293618247948277&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Shri Bharat Mandir is a Google Places sourced visitor location in Rishikesh.'),
    ('bhootnath-temple-rishikesh-rishikesh', 'rishikesh', 'temples', 'Bhootnath Temple Rishikesh', '4889+J6Q, Swargashram Rd, Swarg Ashram, Rishikesh, Uttarakhand 249304, India', 30.116598099999997, 78.318098, 'ChIJkapWA2sWCTkR-MlR6cDJkIs', 'https://maps.google.com/?cid=10056759798303672824&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Bhootnath Temple Rishikesh is a Google Places sourced visitor location in Rishikesh.'),
    ('rishikesh-view-point-rishikesh', 'rishikesh', 'viewpoints', 'Rishikesh View Point', 'Unnamed Road, Lakshman Jhula, Laxman Jhula, Rishikesh, Jonk, Uttarakhand 249302, India', 30.1212342, 78.3271974, 'ChIJC79trUIWCTkR-BppIZRZ9IA', 'https://maps.google.com/?cid=9292150423922744056&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Rishikesh View Point is a Google Places sourced visitor location in Rishikesh.'),
    ('sun-set-point-ganga-view-trek-rishikesh', 'rishikesh', 'viewpoints', 'Sun Set Point Ganga View Trek', '48PX+V3C, Neergarh Waterfall Rd, Rishikesh, Kyarki, Uttarakhand 249192, India', 30.137184999999995, 78.3476398, 'ChIJ70MfV_sXCTkRJOxu3G3rxs0', 'https://maps.google.com/?cid=14827797680246156324&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Sun Set Point Ganga View Trek is a Google Places sourced visitor location in Rishikesh.'),
    ('ganga-view-rest-point-rishikesh', 'rishikesh', 'viewpoints', 'Ganga view & Rest point', '4896+285, Swarg Ashram, Rishikesh, Uttarakhand 249304, India', 30.117503199999998, 78.3108724, 'ChIJ57d7t34XCTkRAXn0nJhfg1Q', 'https://maps.google.com/?cid=6089816230207977729&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Ganga view & Rest point is a Google Places sourced visitor location in Rishikesh.'),
    ('triveni-ghat-rishikesh', 'rishikesh', 'viewpoints', 'Triveni Ghat', 'Triveni Ghat, Mayakund, Rishikesh, Uttarakhand 249201, India', 30.103734399999997, 78.2993218, 'ChIJJ6F4g8Y9CTkRywQ8V2Rjtls', 'https://maps.google.com/?cid=6608578785824212171&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Triveni Ghat is a Google Places sourced visitor location in Rishikesh.'),
    ('khiska-banda-s-rishikesh-view-point-rishikesh', 'rishikesh', 'viewpoints', 'Khiska banda''s Rishikesh view point', '48MJ+M4W, Haridwar Rishikesh Badrinath Rd, Tapovan, Jonk, Uttarakhand 249192, India', 30.1342492, 78.33033619999999, 'ChIJFSYxISgXCTkRjiM-Oqz3vUQ', 'https://maps.google.com/?cid=4953387484261000078&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Khiska banda''s Rishikesh view point is a Google Places sourced visitor location in Rishikesh.'),
    ('shri-kashi-vishwanath-temple-varanasi', 'varanasi', 'temples', 'Shri Kashi Vishwanath Temple', 'Lahori Tola, Varanasi, Uttar Pradesh 221001, India', 25.3108532, 83.0106783, 'ChIJFwuU7iEujjkRE3v7zU8OYEg', 'https://maps.google.com/?cid=5215184104416049939&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Shri Kashi Vishwanath Temple is a Google Places sourced visitor location in Varanasi.'),
    ('shri-kaal-bhairav-temple-varanasi-varanasi', 'varanasi', 'temples', 'Shri Kaal Bhairav Temple, (Varanasi)', 'K30/51-53-55 Ghasi Tola, Bibi Hatiya, Golghar, Kotwali, Varanasi, Uttar Pradesh 221001, India', 25.3176573, 83.0159247, 'ChIJV6gSa3wujjkRx-kXI0C4P4U', 'https://maps.google.com/?cid=9601595516183374279&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Shri Kaal Bhairav Temple, (Varanasi) is a Google Places sourced visitor location in Varanasi.'),
    ('shri-kashi-vishwanath-ji-temple-bhu-campus-varanasi-varanasi', 'varanasi', 'temples', 'Shri Kashi Vishwanath Ji Temple, BHU Campus (Varanasi)', 'Hindu University, Varanasi, Uttar Pradesh 221005, India', 25.2659362, 82.9879509, 'ChIJQYx20zwzjjkRK7fg8H0b-_U', 'https://maps.google.com/?cid=17724790986172839723&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Shri Kashi Vishwanath Ji Temple, BHU Campus (Varanasi) is a Google Places sourced visitor location in Varanasi.'),
    ('shri-satyanarayan-tulsi-manas-temple-varanasi-varanasi', 'varanasi', 'temples', 'Shri Satyanarayan Tulsi Manas Temple, (Varanasi)', 'Durgakund, Anandbagh, Bhelupur, Varanasi, Uttar Pradesh 221005, India', 25.2871825, 83.0003588, 'ChIJY_SjpfMxjjkRn8Lo6e2VlNY', 'https://maps.google.com/?cid=15462148269733888671&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Shri Satyanarayan Tulsi Manas Temple, (Varanasi) is a Google Places sourced visitor location in Varanasi.'),
    ('dashashwamedh-ghat-varanasi', 'varanasi', 'temples', 'Dashashwamedh Ghat', 'Dashashwamedh Ghat Rd, Ghats of Varanasi, Godowlia, Varanasi, Uttar Pradesh 221001, India', 25.306253899999998, 83.0102193, 'ChIJZx9BBB4ujjkRPMgcoTbvGqY', 'https://maps.google.com/?cid=11969141977600804924&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Dashashwamedh Ghat is a Google Places sourced visitor location in Varanasi.'),
    ('ganga-view-point-varanasi-varanasi', 'varanasi', 'viewpoints', 'Ganga View Point, (Varanasi)', '8267+FWJ, Ghats of Varanasi, Katesar, Varanasi, Uttar Pradesh 221001, India', 25.311208300000004, 83.01475959999999, 'ChIJyUEhPwAvjjkR2wWSCSswz-w', 'https://maps.google.com/?cid=17063910474532390363&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Ganga View Point, (Varanasi) is a Google Places sourced visitor location in Varanasi.'),
    ('assi-ghat-varanasi-varanasi', 'varanasi', 'viewpoints', 'Assi Ghat Varanasi', 'Shivala, Varanasi, Uttar Pradesh 221005, India', 25.289431, 83.006079, 'ChIJtQtO8e0xjjkRjFhDS1MEuIA', 'https://maps.google.com/?cid=9275168188361037964&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Assi Ghat Varanasi is a Google Places sourced visitor location in Varanasi.'),
    ('varanasi-beach-varanasi', 'varanasi', 'viewpoints', 'Varanasi Beach', '8237+W8M, Katesar, Varanasi, Uttar Pradesh 221008, India', 25.3043241, 83.01289709999999, 'ChIJI-oR1I0xjjkRbFu0LLqsr-U', 'https://maps.google.com/?cid=16550637071223774060&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Varanasi Beach is a Google Places sourced visitor location in Varanasi.'),
    ('man-singh-observatory-varanasi', 'varanasi', 'viewpoints', 'Man Singh Observatory', 'Man Mandir Ghat, Dashashwamedh Ghat Rd, Observatory, Man mandir, Bangali Tola, Varanasi, Uttar Pradesh 221001, India', 25.307689999999997, 83.0108097, 'ChIJscGV3-ExjjkRiTekCO0cwJ4', 'https://maps.google.com/?cid=11439174857898866569&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Man Singh Observatory is a Google Places sourced visitor location in Varanasi.'),
    ('chet-singh-ghat-varanasi-varanasi', 'varanasi', 'viewpoints', 'Chet Singh Ghat, (Varanasi)', '72V4+QW6, in front of Chet Singh fort, Ghats of Varanasi, Shivala, Varanasi, Uttar Pradesh 221001, India', 25.294417799999998, 83.0072716, 'ChIJ7cArc-8xjjkRZLGO7xpgfpw', 'https://maps.google.com/?cid=11276556185786823012&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Chet Singh Ghat, (Varanasi) is a Google Places sourced visitor location in Varanasi.')
)
insert into public.places (slug, name, level, parent_id, city, state, country, location, address, description, google_place_id, source_url, source_reference, last_verified_at, is_published, is_external, external_source, external_details)
select seed.slug, seed.name, 'attraction'::public.place_level, destination.id, destination.name, destination.state, destination.country, st_setsrid(st_makepoint(seed.longitude, seed.latitude), 4326)::geography, seed.address, seed.description, seed.google_place_id, nullif(seed.source_url, ''), 'Google Places Text Search - controlled catalogue batch', now(), true, false, 'google_places', jsonb_build_object('catalogue_batch', 'generated-google')
from seed join public.places destination on destination.slug = seed.destination_slug
on conflict (slug) do update set parent_id = excluded.parent_id, city = excluded.city, state = excluded.state, country = excluded.country, location = excluded.location, address = excluded.address, description = excluded.description, google_place_id = excluded.google_place_id, source_url = excluded.source_url, source_reference = excluded.source_reference, last_verified_at = excluded.last_verified_at, is_published = true, is_external = false, external_source = excluded.external_source, external_details = excluded.external_details, updated_at = now();

with seed (slug, category_slug) as (values ('shree-neelkanth-mahadev-temple-rishikesh', 'temples'), ('trayambakeshwar-temple-rishikesh-rishikesh', 'temples'), ('parmarth-niketan-ashram-rishikesh', 'temples'), ('shri-bharat-mandir-rishikesh', 'temples'), ('bhootnath-temple-rishikesh-rishikesh', 'temples'), ('rishikesh-view-point-rishikesh', 'viewpoints'), ('sun-set-point-ganga-view-trek-rishikesh', 'viewpoints'), ('ganga-view-rest-point-rishikesh', 'viewpoints'), ('triveni-ghat-rishikesh', 'viewpoints'), ('khiska-banda-s-rishikesh-view-point-rishikesh', 'viewpoints'), ('shri-kashi-vishwanath-temple-varanasi', 'temples'), ('shri-kaal-bhairav-temple-varanasi-varanasi', 'temples'), ('shri-kashi-vishwanath-ji-temple-bhu-campus-varanasi-varanasi', 'temples'), ('shri-satyanarayan-tulsi-manas-temple-varanasi-varanasi', 'temples'), ('dashashwamedh-ghat-varanasi', 'temples'), ('ganga-view-point-varanasi-varanasi', 'viewpoints'), ('assi-ghat-varanasi-varanasi', 'viewpoints'), ('varanasi-beach-varanasi', 'viewpoints'), ('man-singh-observatory-varanasi', 'viewpoints'), ('chet-singh-ghat-varanasi-varanasi', 'viewpoints'))
insert into public.place_categories (place_id, category_id)
select place.id, category.id from seed join public.places place on place.slug = seed.slug join public.categories category on category.slug = seed.category_slug
on conflict do nothing;
