-- Generated from mumbai, goa using 4 throttled Google Places requests.
with seed (slug, destination_slug, category_slug, name, address, latitude, longitude, google_place_id, source_url, description) as (
  values
    ('kyani-co-legendary-irani-restaurant-bakers-mumbai', 'mumbai', 'local-food', 'Kyani & Co. | Legendary Irani Restaurant, Bakers', 'Jer Mahal Building, 657, Jagannath Shankar Seth Rd, opp. Metro Inox Theatre, Marine Lines East, Dhobi Talao, Estate, Marine Lines, Mumbai, Maharashtra 400002, India', 18.9440726, 72.8287473, 'ChIJKQZB3mzO5zsRPQXFAff0kh8', 'https://maps.google.com/?cid=2275150103499310397&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Kyani & Co. | Legendary Irani Restaurant, Bakers is a Google Places sourced visitor location in Mumbai.'),
    ('native-bombay-mumbai', 'mumbai', 'local-food', 'Native Bombay', '10/12, Cochin St, Ballard Estate, Fort, Mumbai, Maharashtra 400001, India', 18.934815999999998, 72.83824710000002, 'ChIJv5GyWavR5zsRTFOxsMKPhpk', 'https://maps.google.com/?cid=11062687601033040716&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Native Bombay is a Google Places sourced visitor location in Mumbai.'),
    ('trishna-mumbai', 'mumbai', 'local-food', 'Trishna', 'Sai Baba Mandir Marg, next to Commerce House, opp. Kalaghoda Cafe, Kala Ghoda, Fort, Mumbai, Maharashtra 400001, India', 18.9286299, 72.8324035, 'ChIJjV68GjzR5zsRu3LYDz5vMDU', 'https://maps.google.com/?cid=3832685595236790971&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Trishna is a Google Places sourced visitor location in Mumbai.'),
    ('pratap-lunch-home-mumbai', 'mumbai', 'local-food', 'Pratap Lunch Home', '79, Janmabhoomi Marg, opposite Siddharth College, Kala Ghoda, Fort, Mumbai, Maharashtra 400001, India', 18.9335359, 72.8328812, 'ChIJ46NQnNzR5zsRB7y2UNoUzTI', 'https://maps.google.com/?cid=3660605000011660295&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Pratap Lunch Home is a Google Places sourced visitor location in Mumbai.'),
    ('gallops-restaurant-mumbai', 'mumbai', 'local-food', 'Gallops Restaurant', 'Inside Mahalaxmi Racecourse, Via, Gate no 1, Keshavrao Khadye Marg, Royal Western India Turf Club, Mahalakshmi, Mumbai, Maharashtra 400034, India', 18.9810633, 72.8172708, 'ChIJu1252lvI5zsR14nH1NzDkTY', 'https://maps.google.com/?cid=3932139302901221847&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Gallops Restaurant is a Google Places sourced visitor location in Mumbai.'),
    ('jehangir-art-gallery-mumbai', 'mumbai', 'photo-spots', 'Jehangir Art Gallery', '161B, Mahatma Gandhi Road, Kala Ghoda, Fort, Mumbai, Maharashtra 400001, India', 18.9273983, 72.83168560000001, 'ChIJCTBgusPR5zsR9jlWzqv4C3Y', 'https://maps.google.com/?cid=8506165738004167158&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Jehangir Art Gallery is a Google Places sourced visitor location in Mumbai.'),
    ('adlem-goi-goa', 'goa', 'local-food', 'Adlem Goi', 'Dauji Road, next to Jamson Wines, Old Goa, Goa 403402, India', 15.5026227, 73.91504499999999, 'ChIJLcZclri_vzsR-LfKNbk4zos', 'https://maps.google.com/?cid=10074051784596961272&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Adlem Goi is a Google Places sourced visitor location in Goa.'),
    ('martin-s-corner-goa', 'goa', 'local-food', 'Martin''s Corner', '69, Binwaddo, Betalbatim, Goa 403713, India', 15.303787999999999, 73.914329, 'ChIJY7N6pt22vzsRld7p1M9Cvgc', 'https://maps.google.com/?cid=557956864238280341&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Martin''s Corner is a Google Places sourced visitor location in Goa.'),
    ('bonita-goa', 'goa', 'local-food', 'Bonita', 'Arossim Beach Rd, Cansaulim, Arossim, Goa 403712, India', 15.336239599999997, 73.8969019, 'ChIJ-0mPaNy3vzsR2NZysXbWX3I', 'https://maps.google.com/?cid=8241541648382875352&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Bonita is a Google Places sourced visitor location in Goa.'),
    ('the-singh-family-restaurant-bar-palolem-goa-goa', 'goa', 'local-food', 'THE SINGH FAMILY RESTAURANT & BAR PALOLEM GOA', 'Main street, opposite blush shop, Palolem, Canacona, Goa 403702, India', 15.0124724, 74.0238834, 'ChIJ7UFiF1FFvjsRP4ear1uGmcs', 'https://maps.google.com/?cid=14670904989482387263&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'THE SINGH FAMILY RESTAURANT & BAR PALOLEM GOA is a Google Places sourced visitor location in Goa.')
)
insert into public.places (slug, name, level, parent_id, city, state, country, location, address, description, google_place_id, source_url, source_reference, last_verified_at, is_published, is_external, external_source, external_details)
select seed.slug, seed.name, 'attraction'::public.place_level, destination.id, destination.name, destination.state, destination.country, st_setsrid(st_makepoint(seed.longitude, seed.latitude), 4326)::geography, seed.address, seed.description, seed.google_place_id, nullif(seed.source_url, ''), 'Google Places Text Search - controlled catalogue batch', now(), true, false, 'google_places', jsonb_build_object('catalogue_batch', 'generated-google')
from seed join public.places destination on destination.slug = seed.destination_slug
on conflict (slug) do update set parent_id = excluded.parent_id, city = excluded.city, state = excluded.state, country = excluded.country, location = excluded.location, address = excluded.address, description = excluded.description, google_place_id = excluded.google_place_id, source_url = excluded.source_url, source_reference = excluded.source_reference, last_verified_at = excluded.last_verified_at, is_published = true, is_external = false, external_source = excluded.external_source, external_details = excluded.external_details, updated_at = now();

with seed (slug, category_slug) as (values ('kyani-co-legendary-irani-restaurant-bakers-mumbai', 'local-food'), ('native-bombay-mumbai', 'local-food'), ('trishna-mumbai', 'local-food'), ('pratap-lunch-home-mumbai', 'local-food'), ('gallops-restaurant-mumbai', 'local-food'), ('jehangir-art-gallery-mumbai', 'photo-spots'), ('adlem-goi-goa', 'local-food'), ('martin-s-corner-goa', 'local-food'), ('bonita-goa', 'local-food'), ('the-singh-family-restaurant-bar-palolem-goa-goa', 'local-food'))
insert into public.place_categories (place_id, category_id)
select place.id, category.id from seed join public.places place on place.slug = seed.slug join public.categories category on category.slug = seed.category_slug
on conflict do nothing;
