-- Generated from ooty, puducherry using 4 throttled Google Places requests.
with seed (slug, destination_slug, category_slug, name, address, latitude, longitude, google_place_id, source_url, description) as (
  values
    ('tamilnadu-tourism-boat-house-ooty-ooty', 'ooty', 'attractions', 'Tamilnadu Tourism Boat House, Ooty', 'N Lake Rd, West Mere, Ooty, Tamil Nadu 643001, India', 11.406293, 76.6878653, 'ChIJgfD1JYG9qDsR7d1ZFDymfcI', 'https://maps.google.com/?cid=14014540392416533997&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Tamilnadu Tourism Boat House, Ooty is a Google Places sourced visitor location in Ooty.'),
    ('thread-garden-ooty', 'ooty', 'attractions', 'Thread Garden', 'CM4Q+Q86, N Lake Rd, opp. Boat House, Kathadimattam, Ooty, Tamil Nadu 643001, India', 11.4069218, 76.6882567, 'ChIJCdvKqHi9qDsRYDiZJ_8wpnI', 'https://maps.google.com/?cid=8261344438896900192&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Thread Garden is a Google Places sourced visitor location in Ooty.'),
    ('c-s-i-st-stephen-s-church-ooty', 'ooty', 'attractions', 'C.S.I St. Stephen''s Church', 'Road, near Collectors office, Club, Upper Bazar, Ooty, Tamil Nadu 643001, India', 11.414672999999999, 76.7022813, 'ChIJC06TtpG9qDsRYWGdDKC6ZDM', 'https://maps.google.com/?cid=3703289990174564705&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'C.S.I St. Stephen''s Church is a Google Places sourced visitor location in Ooty.'),
    ('government-rose-garden-ooty', 'ooty', 'attractions', 'Government Rose Garden', 'Rose garden, Davisdale, Bombay Castle, Ooty, Tamil Nadu 643001, India', 11.406317099999999, 76.70897939999999, 'ChIJy7r1FY29qDsRxqAyJRANvQc', 'https://maps.google.com/?cid=557616291858522310&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Government Rose Garden is a Google Places sourced visitor location in Ooty.'),
    ('ooty-lake-view-point-ooty', 'ooty', 'attractions', 'Ooty Lake View point', 'CM4Q+986, N Lake Rd, Kathadimattam, Ooty, Tamil Nadu 643001, India', 11.4059244, 76.6882704, 'ChIJQYkJGIG9qDsRRth8R75Wb9g', 'https://maps.google.com/?cid=15595779409850456134&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Ooty Lake View point is a Google Places sourced visitor location in Ooty.'),
    ('sugar-dribble-cafe-ooty', 'ooty', 'cafes', 'Sugar Dribble Cafe', 'Inside SANJAY HOTEL , 8/10 USSS BUILDING, GROUND FLOOR, BLOCK Land mark : 1, Kotagiri Rd, Pudumund, Ooty, Tamil Nadu 643001, India', 11.4126877, 76.70883719999999, 'ChIJn4YbmSy9qDsR0kQFJomUOsk', 'https://maps.google.com/?cid=14500065267042043090&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Sugar Dribble Cafe is a Google Places sourced cafe or food venue in Ooty.'),
    ('le-cafe-ooty', 'ooty', 'cafes', 'Le Cafe', 'Littlearth Square, Oriental Buildings, Commissioner''s Road, Summer House Colony, Upper Bazar, Ooty, Tamil Nadu 643001, India', 11.4128873, 76.7023385, 'ChIJSTzAkCW9qDsR0LNMVr0pIqA', 'https://maps.google.com/?cid=11538831088450057168&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Le Cafe is a Google Places sourced cafe or food venue in Ooty.'),
    ('blooming-garden-cafe-ooty-s-only-pet-friendly-garden-cafe-ooty', 'ooty', 'cafes', 'Blooming Garden Cafe- Ooty’s Only Pet Friendly Garden Cafe', 'Tiverton Bungalow, 160, Coonoor Rd, Thalayathimund, Ooty, Tamil Nadu 643001, India', 11.4045767, 76.7146392, 'ChIJt7cnGSW9qDsR4YS5zMhq1-A', 'https://maps.google.com/?cid=16201535595149362401&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Blooming Garden Cafe- Ooty’s Only Pet Friendly Garden Cafe is a Google Places sourced cafe or food venue in Ooty.'),
    ('earl-s-secret-ooty', 'ooty', 'cafes', 'Earl''s Secret', 'Havelock Rd, Police Quarters, Pudumund, Ooty, Tamil Nadu 643001, India', 11.4199915, 76.69828400000002, 'ChIJ_____4i9qDsRy-32zCtecFI', 'https://maps.google.com/?cid=5940351450717023691&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Earl''s Secret is a Google Places sourced cafe or food venue in Ooty.'),
    ('cafe-sunset-boulevard-ooty', 'ooty', 'cafes', 'Cafe Sunset Boulevard', 'Tiger Hl Rd, Thalayathimund, Ooty, Tamil Nadu 643001, India', 11.411388599999999, 76.7206717, 'ChIJUctxI5G9qDsRM0E5Z8z1eCA', 'https://maps.google.com/?cid=2339890264672911667&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Cafe Sunset Boulevard is a Google Places sourced cafe or food venue in Ooty.'),
    ('puducherry-museum-puducherry', 'puducherry', 'attractions', 'Puducherry Museum', 'near rock beach, nearby romain Rollen Library, White Town, Puducherry, 605001, India', 11.9344884, 79.83485, 'ChIJIeb1h9ZjUzoRgdmFmre2eM0', 'https://maps.google.com/?cid=14805784674668239233&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Puducherry Museum is a Google Places sourced visitor location in Puducherry.'),
    ('rock-beach-puducherry', 'puducherry', 'attractions', 'Rock Beach', '23, Laporte St, MG Road Area, Puducherry, 605001, India', 11.9339038, 79.83619569999999, 'ChIJJfOFaCBjUzoRIfJCm_X52q4', 'https://maps.google.com/?cid=12599657740789543457&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Rock Beach is a Google Places sourced visitor location in Puducherry.'),
    ('arulmigu-manakula-vinayagar-devasthanam-puducherry', 'puducherry', 'attractions', 'Arulmigu Manakula Vinayagar Devasthanam', 'WRPM+8F7, R. Manakkula Vinayagar St, White Town, Puducherry, 605001, India', 11.9357756, 79.8336621, 'ChIJHyNdX9RjUzoRxr273LLGdWA', 'https://maps.google.com/?cid=6950680071425998278&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Arulmigu Manakula Vinayagar Devasthanam is a Google Places sourced visitor location in Puducherry.'),
    ('bharathi-park-puducherry-puducherry', 'puducherry', 'attractions', 'Bharathi Park Puducherry', '20, Rue Saint Gilles Street, White Town, Puducherry, 605001, India', 11.9330191, 79.8341938, 'ChIJSW_qs9RjUzoRmeMTilI_akg', 'https://maps.google.com/?cid=5218052741998568345&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Bharathi Park Puducherry is a Google Places sourced visitor location in Puducherry.'),
    ('serenity-beach-puducherry', 'puducherry', 'attractions', 'Serenity Beach', 'XRFV+8W, Kottakuppam, Puducherry, Kottakuppam, Tamil Nadu 605104, India', 11.9733731, 79.8448683, 'ChIJoRP3A6ZjUzoRxMA1IxiNz9A', 'https://maps.google.com/?cid=15046400014877573316&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Serenity Beach is a Google Places sourced visitor location in Puducherry.'),
    ('coromandel-cafe-puducherry', 'puducherry', 'cafes', 'Coromandel Cafe', 'La Maison Rose, 8, Romain Rolland St, White Town, Puducherry, 605001, India', 11.9312917, 79.8341738, 'ChIJhYeDaStiUzoRkzSz_GifbvM', 'https://maps.google.com/?cid=17541132871919678611&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Coromandel Cafe is a Google Places sourced cafe or food venue in Puducherry.'),
    ('bread-chocolate-puducherry', 'puducherry', 'cafes', 'Bread & Chocolate', '6, Marine Street, next to Sri Aurobindo Ashram, White Town, Puducherry, 605001, India', 11.936427, 79.83509939999999, 'ChIJUyNRcvtjUzoROa74RwzEDP8', 'https://maps.google.com/?cid=18378279736418283065&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Bread & Chocolate is a Google Places sourced cafe or food venue in Puducherry.'),
    ('cafe-des-arts-puducherry', 'puducherry', 'cafes', 'Café des Arts', '58, Capitane Marius Xavier St, MG Road Area, Puducherry, 605001, India', 11.9304882, 79.8312705, 'ChIJT21bCCtiUzoRz2HuhAzof0Y', 'https://maps.google.com/?cid=5080034045164675535&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Café des Arts is a Google Places sourced cafe or food venue in Puducherry.'),
    ('le-cafe-puducherry', 'puducherry', 'cafes', 'Le Café', '23, Beach Rd, White Town, Puducherry, 605001, India', 11.9315814, 79.83575890000002, 'ChIJRT6HJGpjUzoR3YIJo9Z6Hn8', 'https://maps.google.com/?cid=9159893754395067101&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Le Café is a Google Places sourced cafe or food venue in Puducherry.'),
    ('ciclo-cafe-puducherry', 'puducherry', 'cafes', 'Ciclo Café', 'Ciclo Cafe, No:23, Romain Rolland St, White Town, Puducherry, 605001, India', 11.9269983, 79.83342019999999, 'ChIJTVgOlexjUzoRMdBEYCVu9us', 'https://maps.google.com/?cid=17002898549991854129&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Ciclo Café is a Google Places sourced cafe or food venue in Puducherry.')
)
insert into public.places (slug, name, level, parent_id, city, state, country, location, address, description, google_place_id, source_url, source_reference, last_verified_at, is_published, is_external, external_source, external_details)
select seed.slug, seed.name, 'attraction'::public.place_level, destination.id, destination.name, destination.state, destination.country, st_setsrid(st_makepoint(seed.longitude, seed.latitude), 4326)::geography, seed.address, seed.description, seed.google_place_id, nullif(seed.source_url, ''), 'Google Places Text Search - controlled catalogue batch', now(), true, false, 'google_places', jsonb_build_object('catalogue_batch', 'generated-google')
from seed join public.places destination on destination.slug = seed.destination_slug
on conflict (slug) do update set parent_id = excluded.parent_id, city = excluded.city, state = excluded.state, country = excluded.country, location = excluded.location, address = excluded.address, description = excluded.description, google_place_id = excluded.google_place_id, source_url = excluded.source_url, source_reference = excluded.source_reference, last_verified_at = excluded.last_verified_at, is_published = true, is_external = false, external_source = excluded.external_source, external_details = excluded.external_details, updated_at = now();

with seed (slug, category_slug) as (values ('tamilnadu-tourism-boat-house-ooty-ooty', 'attractions'), ('thread-garden-ooty', 'attractions'), ('c-s-i-st-stephen-s-church-ooty', 'attractions'), ('government-rose-garden-ooty', 'attractions'), ('ooty-lake-view-point-ooty', 'attractions'), ('sugar-dribble-cafe-ooty', 'cafes'), ('le-cafe-ooty', 'cafes'), ('blooming-garden-cafe-ooty-s-only-pet-friendly-garden-cafe-ooty', 'cafes'), ('earl-s-secret-ooty', 'cafes'), ('cafe-sunset-boulevard-ooty', 'cafes'), ('puducherry-museum-puducherry', 'attractions'), ('rock-beach-puducherry', 'attractions'), ('arulmigu-manakula-vinayagar-devasthanam-puducherry', 'attractions'), ('bharathi-park-puducherry-puducherry', 'attractions'), ('serenity-beach-puducherry', 'attractions'), ('coromandel-cafe-puducherry', 'cafes'), ('bread-chocolate-puducherry', 'cafes'), ('cafe-des-arts-puducherry', 'cafes'), ('le-cafe-puducherry', 'cafes'), ('ciclo-cafe-puducherry', 'cafes'))
insert into public.place_categories (place_id, category_id)
select place.id, category.id from seed join public.places place on place.slug = seed.slug join public.categories category on category.slug = seed.category_slug
on conflict do nothing;
