-- Generated from munnar, udaipur using 2 throttled Google Places requests.
with seed (slug, destination_slug, category_slug, name, address, latitude, longitude, google_place_id, source_url, description) as (
  values
    ('kolukkumalai-tea-estate-munnar', 'munnar', 'attractions', 'Kolukkumalai Tea Estate', '33Q5+HRC, Kolukkumalai, Suryanelli, Munnar, Kerala 685612, India', 10.0889332, 77.0595247, 'ChIJL19HlRWZBzsRUkAX_NUWwkk', 'https://maps.google.com/?cid=5314835618563833938&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Kolukkumalai Tea Estate is a Google Places sourced visitor location in Munnar.'),
    ('the-blossom-hydel-park-munnar', 'munnar', 'attractions', 'The Blossom Hydel Park', 'Bus Stand, Highway, Munnar - Aluva Rd, near KSRTC, Moolakadai, Munnar, Kerala 685612, India', 10.0692928, 77.0667452, 'ChIJf6KbNw2ZBzsRXj_m_4rZQlo', 'https://maps.google.com/?cid=6504000002898411358&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'The Blossom Hydel Park is a Google Places sourced visitor location in Munnar.'),
    ('i-love-munnar-munnar', 'munnar', 'attractions', 'I Love Munnar', '33J6+JRJ Devikulam Y Junction, bridge, near Sujatha Inn, Moolakadai, Munnar, Kerala 685612, India', 10.0815582, 77.0619682, 'ChIJqR_lcaeZBzsRV7oU_bWbivo', 'https://maps.google.com/?cid=18053413262205434455&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'I Love Munnar is a Google Places sourced visitor location in Munnar.'),
    ('munnar-rose-garden-munnar', 'munnar', 'attractions', 'Munnar Rose Garden', 'Munnar - Aluva Rd, Rose Nagar, Mattupetty, Munnar, Kerala 685612, India', 10.0860013, 77.0755241, 'ChIJq39-6WaZBzsR4xuhg5SQ7yw', 'https://maps.google.com/?cid=3237965624640609251&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Munnar Rose Garden is a Google Places sourced visitor location in Munnar.'),
    ('tea-museum-munnar', 'munnar', 'attractions', 'Tea Museum', 'KDHP House, NH 49, Nullatanni, Munnar, Kannan Devan Hills, Kerala 685612, India', 10.0941757, 77.05072, 'ChIJ-XEBiCmaBzsREcK0GZ5hYdQ', 'https://maps.google.com/?cid=15303620340445659665&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Tea Museum is a Google Places sourced visitor location in Munnar.'),
    ('saheliyon-ki-bari-udaipur', 'udaipur', 'attractions', 'Saheliyon ki bari', 'Panchwati, Udaipur, Rajasthan 313001, India', 24.603006399999998, 73.6854901, 'ChIJd9K3fdflZzkRQeScJCCgYZ0', 'https://maps.google.com/?cid=11340521396609279041&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Saheliyon ki bari is a Google Places sourced visitor location in Udaipur.'),
    ('city-palace-udaipur', 'udaipur', 'attractions', 'City Palace', 'Old City, Udaipur, Rajasthan 313001, India', 24.576442099999998, 73.6835109, 'ChIJ1adZBmTlZzkRDqvq-navV5I', 'https://maps.google.com/?cid=10545089978061990670&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'City Palace is a Google Places sourced visitor location in Udaipur.'),
    ('ambrai-ghat-udaipur', 'udaipur', 'attractions', 'Ambrai Ghat', 'Chandpole Maji, Ka Mandir corner of Lake, Cheerwa, Pichola, Udaipur, Rajasthan 313004, India', 24.5775547, 73.67990209999999, 'ChIJf1CpH2flZzkRmiCtzPDYk4A', 'https://maps.google.com/?cid=9264987387168891034&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Ambrai Ghat is a Google Places sourced visitor location in Udaipur.'),
    ('bagore-ki-haveli-udaipur', 'udaipur', 'attractions', 'Bagore Ki Haveli', 'HMHJ+WV5, Hotel Gangaur Palace, Pichola, Udaipur, Rajasthan 313004, India', 24.5797664, 73.6822359, 'ChIJA_ZPmxzlZzkRDSB9_ReyOfM', 'https://maps.google.com/?cid=17526235240995823629&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Bagore Ki Haveli is a Google Places sourced visitor location in Udaipur.'),
    ('monsoon-palace-udaipur', 'udaipur', 'attractions', 'Monsoon Palace', 'Udaipur, Kodiyat, Rajasthan 313031, India', 24.5931853, 73.6396056, 'ChIJw7A_ucr6ZzkRJTV3E4HVc4A', 'https://maps.google.com/?cid=9255976409530578213&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA', 'Monsoon Palace is a Google Places sourced visitor location in Udaipur.')
)
insert into public.places (slug, name, level, parent_id, city, state, country, location, address, description, google_place_id, source_url, source_reference, last_verified_at, is_published, is_external, external_source, external_details)
select seed.slug, seed.name, 'attraction'::public.place_level, destination.id, destination.name, destination.state, destination.country, st_setsrid(st_makepoint(seed.longitude, seed.latitude), 4326)::geography, seed.address, seed.description, seed.google_place_id, nullif(seed.source_url, ''), 'Google Places Text Search - controlled catalogue batch', now(), true, false, 'google_places', jsonb_build_object('catalogue_batch', 'generated-google')
from seed join public.places destination on destination.slug = seed.destination_slug
on conflict (slug) do update set parent_id = excluded.parent_id, city = excluded.city, state = excluded.state, country = excluded.country, location = excluded.location, address = excluded.address, description = excluded.description, google_place_id = excluded.google_place_id, source_url = excluded.source_url, source_reference = excluded.source_reference, last_verified_at = excluded.last_verified_at, is_published = true, is_external = false, external_source = excluded.external_source, external_details = excluded.external_details, updated_at = now();

with seed (slug, category_slug) as (values ('kolukkumalai-tea-estate-munnar', 'attractions'), ('the-blossom-hydel-park-munnar', 'attractions'), ('i-love-munnar-munnar', 'attractions'), ('munnar-rose-garden-munnar', 'attractions'), ('tea-museum-munnar', 'attractions'), ('saheliyon-ki-bari-udaipur', 'attractions'), ('city-palace-udaipur', 'attractions'), ('ambrai-ghat-udaipur', 'attractions'), ('bagore-ki-haveli-udaipur', 'attractions'), ('monsoon-palace-udaipur', 'attractions'))
insert into public.place_categories (place_id, category_id)
select place.id, category.id from seed join public.places place on place.slug = seed.slug join public.categories category on category.slug = seed.category_slug
on conflict do nothing;
